### PR TITLE
Add LICENSE to project

### LINKED ISSUE #2: Project missing LICENSE file

### PR DESCRIPTION
**Pull request by kshithijiyer**
Fixes: #2

### CODE REVIEW

**Review by jbw976 — CHANGES_REQUESTED** [review]
Thanks for noticing this and making this contribution!

I believe this should be the same license as the rest of the Rook codebase, which is Apache 2: https://github.com/rook/rook/blob/master/LICENSE

Would you mind updating this file to match the Apache 2 one from main rook/rook repo?

**Comment by kshithijiyer** [comment]
> Thanks for noticing this and making this contribution!
> 
> I believe this should be the same license as the rest of the Rook codebase, which is Apache 2: https://github.com/rook/rook/blob/master/LICENSE
> 
> Would you mind updating this file to match the Apache 2 one from main rook/rook repo?

Done @jbw976

**Review by jbw976 — APPROVED** [review]

**Comment by jbw976** [comment]
@sebastian-philipp @travisn any idea about the failing CI build on this PR? https://github.com/rook/rook-client-python/pull/3/checks?check_run_id=1668554351

relevant snippet?
```
    def _property_from_json(data, breadcrumb, name, py_name, typ, required, nullable):
>       if not required and name not in data:
E       TypeError: argument of type 'NoneType' is not iterable

rook_client/_helper.py:21: TypeError
```

**Comment by sebastian-philipp** [comment]
unrelated

**Pull request merged**
